# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.TimeField()),
                ('active_time', models.TimeField()),
                ('nick', models.CharField(max_length=20)),
                ('_url', models.CharField(max_length=50)),
                ('_params', models.CharField(max_length=500)),
                ('_cookie', models.CharField(max_length=500)),
                ('_always_do', models.SmallIntegerField(default=0)),
                ('_interval_time', models.FloatField(default=0.5)),
                ('_is_random', models.SmallIntegerField(default=1)),
                ('_depth', models.SmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UrlTemporaryStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField()),
                ('next_id', models.IntegerField()),
                ('_current_crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_storage', to='running_crawler.CrawlerBase')),
            ],
        ),
    ]
