# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacingData',
            fields=[
                ('term_num', models.IntegerField(primary_key=True, serialize=False)),
                ('lottery_time', models.TimeField(auto_now=True)),
                ('n1', models.SmallIntegerField()),
                ('n2', models.SmallIntegerField()),
                ('n4', models.SmallIntegerField()),
                ('n5', models.SmallIntegerField()),
                ('n6', models.SmallIntegerField()),
                ('n7', models.SmallIntegerField()),
                ('n8', models.SmallIntegerField()),
                ('n9', models.SmallIntegerField()),
                ('n10', models.SmallIntegerField()),
            ],
        ),
    ]
